### ISSUE TITLE
Add partner-specific parameters

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/benchmark-tools#4]
This should add support to `dna`, `cg` and `shape`

**Comment by rvhonorato** [comment]
After #20, these can be injected in the `.yaml` over `run_cns`;

```yaml
general:
   # ...
scenarios:
  - name: custom
    parameters:
      run_cns:
        shape_mol1: false
        # ...
```
