### ISSUE TITLE
Duplicated parameters when module `_fname` suffixes overlap

### ISSUE THREAD

**Issue by rvhonorato** [haddocking/benchmark-tools#50]
### Bug Description

If, for multiple scenarios, the `_fname` suffixes overlap;

* `_ti`
* `_ti_something`

It will result in duplicated parameters 

```toml
[rigidbody]
# ...
ambig_fname = "../data/PDB_ti.tbl"
ambig_fname = "../data/PDB_ti_something.tbl"
```

Nice catch by @padraic-hug 👍🏽 

### Expected Behavior

Not writing duplicated parameters

### Possible Solution

If the suffixes overlap, it is very tricky do pick to which each belong, so its simpler to not allow suffixes that can match each other.

## Steps to Reproduce

1. Write a `.yaml` that looks like:
```yaml
general:
  # ...
scenarios:
  - name: s1
    parameters:
      modules:
        # ...
        flexref:
          ambig_fname: _ti
  - name: s2
    parameters:
      modules:
        # ...
        flexref:
          ambig_fname: _ti_something
```
